/**
 * UCG Manifest - Tracks installed files for uninstall and smart updates.
 * Writes _bmad/_config/ucg-manifest.yaml after each install.
 */

const path = require('node:path');
const fs = require('fs-extra');
const yaml = require('js-yaml');

const MANIFEST_DIR = '_bmad/_config';
const MANIFEST_FILE = 'ucg-manifest.yaml';

/**
 * Recursively collect all file paths under a directory,
 * returned as paths relative to projectDir.
 */
async function collectFiles(dir, projectDir) {
  const files = [];
  if (!(await fs.pathExists(dir))) return files;

  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const subFiles = await collectFiles(fullPath, projectDir);
      files.push(...subFiles);
    } else {
      files.push(path.relative(projectDir, fullPath));
    }
  }
  return files;
}

/**
 * Build and write the manifest after installation.
 *
 * @param {string} projectDir - Project root
 * @param {object} config - Install config (ucgFolder, ides, etc.)
 * @param {object} options - Additional info (version, ideDirectories)
 */
async function writeManifest(projectDir, config, options = {}) {
  const ucgFolder = config.ucgFolder || '_bmad/ucg';
  const ucgDir = path.join(projectDir, ucgFolder);

  // Collect all installed files
  const ucgFiles = await collectFiles(ucgDir, projectDir);

  // Collect IDE skill directory files (installed to each IDE's skills/ dir)
  const ideDirectories = options.ideDirectories || [];
  const ideSkillFiles = [];
  for (const ideDir of ideDirectories) {
    const fullDir = path.join(projectDir, ideDir);
    const files = await collectFiles(fullDir, projectDir);
    ideSkillFiles.push(...files);
  }

  // Collect learning material files
  const learnDir = path.join(projectDir, '_ucg-learn');
  const learnFiles = await collectFiles(learnDir, projectDir);

  const manifest = {
    version: options.version || 'unknown',
    installed_at: new Date().toISOString(),
    action: config._action || 'fresh',
    module: 'ucg',
    ucg_folder: ucgFolder,
    ides: config.ides || [],
    directories: [ucgFolder, ...ideDirectories, ...(learnFiles.length > 0 ? ['_ucg-learn'] : [])],
    // Help-catalog rows registered for bmad-help routing (removed row-wise on
    // uninstall — the catalog files are shared, never deleted wholesale here)
    help_catalog: options.helpCatalog || null,
    files: {
      ucg: ucgFiles,
      ide_skills: ideSkillFiles,
      learning: learnFiles,
    },
  };

  const manifestDir = path.join(projectDir, MANIFEST_DIR);
  await fs.ensureDir(manifestDir);

  const yamlStr = yaml.dump(manifest, { lineWidth: -1, sortKeys: false });
  await fs.writeFile(
    path.join(manifestDir, MANIFEST_FILE),
    `# UCG Installation Manifest - Generated by installer\n# Do not edit manually\n${yamlStr}`,
    'utf8',
  );
}

/**
 * Read an existing manifest, or return null if none exists.
 */
async function readManifest(projectDir) {
  const manifestPath = path.join(projectDir, MANIFEST_DIR, MANIFEST_FILE);
  try {
    const content = await fs.readFile(manifestPath, 'utf8');
    return yaml.load(content) || null;
  } catch {
    return null;
  }
}

module.exports = { writeManifest, readManifest, MANIFEST_DIR, MANIFEST_FILE };
